CREATE ROLE reader NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS LOGIN;
GRANT EXECUTE ON FUNCTION pg_config TO reader;
GRANT SELECT ON pg_catalog.pg_config TO reader;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO reader;
